name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Replace with the desired Node.js version

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.ACR_REGISTRY }}/wordwelder-fe:latest .
          docker login ${{ secrets.ACR_REGISTRY }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
          docker push ${{ secrets.ACR_REGISTRY }}/wordwelder-fe:latest

      - name: Deploy to Azure Web App
        run: |
          az webapp config container set --name ${{ secrets.FRONTEND_APP_NAME }} --resource-group wordwelder --docker-custom-image-name ${{ secrets.ACR_REGISTRY }}/wordwelder-fe:latest --docker-registry-server-url https://${{ secrets.ACR_REGISTRY }}
      - name: Apply env variables
        run: |
          az webapp config appsettings set --name ${{ secrets.FRONTEND_APP_NAME }} --resource-group wordwelder --settings REACT_APP_API_HOST=${{ secrets.BE_APP_ADDRESS }}
